# Generated by Django 4.2.21 on 2025-05-13 22:08

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=api.models.get_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PredictionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction', models.FloatField()),
                ('is_malignant', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scan_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='api.scanimage')),
            ],
        ),
    ]
